#!/usr/bin/env perl

use Modern::Perl qw/2020/;

# Set the output encoding to UTF-8
binmode STDOUT, q{:encoding(UTF-8)};
binmode STDERR, q{:encoding(UTF-8)};

# This allows us to find our own libs which are shared by the Trawler.
use FindBin qw/$Bin/;
use lib qq{$Bin/../../lib};

use Mojo::File 'curfile';
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('TrawlWeb');
