name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2.0.0

      - name: Docker Build & Push to GitHub Package
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USER_NAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_KEY }}
          DOCKERFILE: "Dockerfile"
          TAG_NAME: "v0.0.1-beta1"
          LATEST: "true"
