name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Build & Push to GitHub Package
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: ${{ secrets.GITHUB_USERNAME }}
        PASSWORD: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
        REGISTRY: "docker.pkg.github.com"
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: "org-version-trawler"
        TAG_NAME: "v0.0.1"
        LATEST: "true"
